### ISSUE TITLE
Do we have to use read and write functions?

### ISSUE THREAD

**Issue by erolasan** [rurico/schedule_controller#1]
Hi, 
I am trying to just schedule a method to run at a specific time of the day but the controller returns a null pointer exception if I haven't implemented the read and write functions. Do I have to implement them in order for the controller to work?

**Comment by rurico** [comment]
Sorry for the late reply @erolasan.
Yes, you need to use the read/write function. If you do not use this feature, clients will lose their last timing data after the resumption.

**Comment by rurico** [comment]
also, you can use the TimeCalculator to make a schedule.
```dart
final timeCalculator = TimeCalculator();
final timestamp = timeCalculator.timestamp;
final dayStartTimeDiff = timeCalculator.dayStartTimeDiff(timestamp);
final scheduleDuration = Duration(milliseconds: dayStartTimeDiff);
Future.delayed(scheduleDuration, callback);
```
If your storage logic is on the network, maybe use the write/read functions not adverse.
